# Copyright (C) 2022 tt.bot dev team
# 
# This file is part of @tt-bot-dev/web.
# 
# @tt-bot-dev/web is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# @tt-bot-dev/web is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with @tt-bot-dev/web.  If not, see <http://www.gnu.org/licenses/>.


lint:
  stage: test
  image: node:current-alpine
  script:
    - rm package.json
    - npm i @tt-bot-dev/eslint-config @typescript-eslint/eslint-plugin @typescript-eslint/parser
    - npx eslint --ext .js,.ts,.mjs,.mts .

test_build:
  stage: test
  image: node:current-alpine
  script:
    - apk add git
    - rm /usr/local/bin/yarn
    - rm /usr/local/bin/yarnpkg
    - npm i -g corepack
    - corepack prepare yarn@stable --activate
    - yarn install --mode=skip-build
    - yarn run build::server
    - yarn run build::client